name: Generate Daily Release
on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 2 * * *"
    - cron: "0 4 * * *"
    - cron: "0 6 * * *"
    - cron: "0 8 * * *"
    - cron: "0 10 * * *"
    - cron: "0 12 * * *"
    - cron: "0 14 * * *"
    - cron: "0 15 * * *"

env:
  REPO: nugu-linux
  REPOSLUG: nugu-developers/nugu-linux

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: |
          echo "github = $GITHUB_CONTEXT"
          echo "event = $GITHUB_EVENT"
          echo "action_path = ${{ github.action_path }}"
          echo "actor = ${{ github.actor }}"
          echo "base_ref = ${{ github.base_ref }}"
          echo "event_name = ${{ github.event_name }}"
          echo "event_path = ${{ github.event_path }}"
          echo "workflow = ${{ github.workflow }}"
          echo "workspace = ${{ github.workspace }}"
          echo "action_path = ${{ github.action_path }}"
          date
          TZ=UTC date
          TZ=Asia/Seoul date
